s3tests/functional/test_s3.py

@yehudasa 
Test for bug #10311
Signed-off-by: Ray Lv <raylv@yahoo-inc.com>

s3tests: add regression test for bug #10311 - rgw: Object is deleted automatically if conditional PUT returns 412

---

s3tests/functional/test_s3.py

Note: please pull this one in only after the corresponding pull request to ceph.git has been pulled.
Tests issue #10770: bad bucket index entry on bucket index cancelled
operation.
Signed-off-by: Yehuda Sadeh <yehuda@inktank.com>

rgw: concurrent non-versioned object creation, deletion

---

s3tests/functional/test_s3.py

Test setting container ACLs during create bucket

---

s3tests/functional/__init__.py

Handle empty bucket while nuking

---

s3tests/functional/test_s3.py

Test range get with invalid range

---

s3tests/functional/test_s3.py

Test Content-Range header in range requests

---

s3tests/functional/test_headers.py
s3tests/fuzz/test/test_fuzzer.py

Signed-off-by: Robin H. Johnson <robbat2@gentoo.org>

tests must have unique names, otherwise they override existing tests.

---

bootstrap

Fixes: 12302
Signed-off-by: Dan Mick <dan.mick@redhat.com>

Remove "--allow-hosts None" because it magically makes things work

---

request_decision_graph.yml

Signed-off-by: Robin H. Johnson <robbat2@gentoo.org>

fuzz: Write fuzzer rules for WebsiteConfiguration.

---

s3tests/functional/test_s3.py

Add tests for Cache-Control and Expires headers

---

s3tests/functional/test_s3.py

Add multipart tests with invalid parts

---

s3tests/functional/test_s3.py

Add RequestId on error tests
See https://github.com/ceph/ceph/pull/5866

Test RequestId on error

---

s3tests/functional/test_s3.py

Check content is correct on copy multipart

s3tests: Check content is correct on copy multipart

---

s3tests/functional/test_s3.py

Copy tests for non-existent buckets and keys

---

s3tests/functional/test_s3.py

Anonymously list private and public-read buckets

---

s3tests/functional/test_s3.py

Add test for HEAD of a zero-byte object

---

s3tests/functional/test_s3.py

Test begin to overwrite file with MPU then abort

---

s3tests/functional/test_s3.py

Test X-Amz-Expires under AWS4 auth
$ S3_USE_SIGV4=1 S3TEST_CONF=./s3tests.conf ./virtualenv/bin/nosetests s3tests/functional/test_s3.py -a auth_aws4 -v
s3tests.functional.test_s3.test_object_raw_get_x_amz_expires_not_expired ... ok
s3tests.functional.test_s3.test_object_raw_get_x_amz_expires_out_range_zero ... ok
s3tests.functional.test_s3.test_object_raw_get_x_amz_expires_out_max_range ... ok
s3tests.functional.test_s3.test_object_raw_get_x_amz_expires_out_positive_range ... ok
----------------------------------------------------------------------
Ran 4 tests in 4.784s
OK

rgw: add X-Amz-Expires test cases

---

s3tests/functional/test_s3.py

rgw: add a few tests that check for null object versioning behavior

---

s3tests/functional/test_s3.py

Add fails_on_rgw on multipart copy part tests

---

s3tests/functional/test_s3.py

Add tests for conditional gets

---

s3tests/functional/test_s3.py

Use key's last_modified instead of local time

s3tests: modify test_get_object_ifmodifiedsince_failed

---

bootstrap

add missing libxml2-dev and libxslt-dev dependencies

---

s3tests/functional/test_s3.py

test for the following ceph issue:
http://tracker.ceph.com/issues/15886

rgw: add a new multipart test

---

s3tests/functional/test_s3.py

Add range request to an empty object

---

s3tests/functional/test_s3.py

test get object with special key name

---

s3tests/functional/test_s3.py

Add testing for copy object to/from a versioned bucket

---

s3tests/functional/test_s3.py

Test S3 lifecycle expiration.  This requires the test harnass code in
RGW to make sure it doesn't take days so expire anything.
Signed-off-by: Daniel Gryniewicz <dang@redhat.com>
Needs the same PR for ceph-qa-suite

S3 lifecycle tests

---

s3tests/functional/test_s3.py

test set_acl for keys with special characters

---

s3tests/functional/test_headers.py

Signed-off-by: Yehuda Sadeh yehuda@redhat.com

rgw: skip aws2 requests when testing aws4

---

s3tests/functional/test_s3.py

Signed-off-by: Yehuda Sadeh yehuda@redhat.com

add a test for post object with empty conditions

---

s3tests/functional/test_s3.py

Signed-off-by: Yehuda Sadeh yehuda@redhat.com

more multipart copy tests

---

s3tests/functional/test_s3.py

Fixes: http://tracker.ceph.com/issues/18023

test multi-delete with object with ending underscore

---

bootstrap

Deal setuptools upgrade problem discussed here:
https://github.com/pypa/setuptools/issues/940

bootstrap:  force new setuptools

---

s3tests/functional/test_s3.py

Lifecycle validation is add in https://github.com/ceph/ceph/pull/12750. 
S3test need some test cases about that. The error status and error code are the same as S3.
Fixes: http://tracker.ceph.com/issues/18541

add lifecycle validate test cases.

---

s3tests/functional/test_s3.py

According to https://tools.ietf.org/html/rfc7232, If-Match field should looks like QUOTES ETag QUOTES.

Fix If-Match test

---

s3tests/functional/test_s3.py

These cases are for non-current version object expiration and multipart upload expiration in s3 lifecycle. Related features are in https://github.com/ceph/ceph/pull/13622 and https://github.com/ceph/ceph/pull/13385 .
Because boto doesn't support those features, so the xml body is generated manually.
Fixes: http://tracker.ceph.com/issues/19519

Test case for non-current expiration，multipart upload expiration and delete marker expiration

---

s3tests/functional/test_s3.py

This test case is for the bug fix https://github.com/ceph/ceph/pull/14117 
Fixes: http://tracker.ceph.com/issues/19565

Add test case for getting version id when getting object and object's metadata

---

s3tests/functional/test_s3.py

Signed-off-by: Pritha Srivastava <prsrivas@redhat.com>

rgw: Adding tests for Bucket Policy.

---

s3tests/functional/test_s3.py

This is for https://github.com/ceph/ceph/pull/15807

add test case for lifecycle expiration date.

---

s3tests/functional/test_s3.py

Add test for bucket list with prefix with underscore

---

s3tests/functional/test_s3.py

add test case for https://github.com/ceph/ceph/pull/15607

add test case: test set policy with condition operator end with IfExists

---

s3tests/functional/test_s3.py

Tests to accompany https://github.com/ceph/ceph/pull/13753 object
tagging functionality

add tests for tagging functionality

---

s3tests/functional/test_s3.py

Add test for invalid copy part range

---

s3tests/functional/test_s3.py

Part of backport tracker http://tracker.ceph.com/issues/19764
Fixes: http://tracker.ceph.com/issues/18923

jewel: Add a test case for setting acl on object with no version id specified.

---

s3tests/functional/test_s3.py

https://github.com/ceph/ceph/pull/15994

Data encryption is not follow the AWS agreement

---

s3tests/functional/test_headers.py

tests for https://github.com/ceph/ceph/pull/15467

check precedence of Date and X-Amz-Date in signatures

---

s3tests/functional/test_s3.py

cherry-picking the LC fixes to ceph-master, we cant forward master to ceph-master yet because it looks like the test for invalid copy range doesn't pass yet

add the LC fixes to ceph-master

---

s3tests/functional/test_s3.py

This test case is used for testing whether a version-id header is returned when upload files.
Related with [ceph #18935](https://github.com/ceph/ceph/pull/18935)
Signed-off-by: Xinying Song <songxinying@cloudin.cn>

Add test case for getting version-id when upload objects  bucket

---

s3tests/functional/test_s3.py

Add test case for POST with no Content-Type header

---

s3tests/functional/test_s3.py

@cbodley 
As we talked in https://github.com/ceph/ceph/pull/20226, you could verify the case, thanks

compression: add case to download range from big object

---

s3tests_boto3/functional/test_s3.py

Add boto3 tests for non-standard s3 functionality -- list bucket unordered.
Signed-off-by: J. Eric Ivancich <ivancich@redhat.com>

boto3: Unordered bucket listing

---

s3tests/functional/test_s3.py

for  https://github.com/ceph/ceph/pull/21285 test
Signed-off-by: yuliyang <yuliyang@cmss.chinamobile.com>

enable test for https://github.com/ceph/ceph/pull/21285

---

s3tests/functional/test_s3.py

test for https://github.com/ceph/ceph/pull/18556
Signed-off-by: yuliyang <yuliyang@cmss.chinamobile.com>

rgw: test cors option request with Access-Control-Request-Headers

---

s3tests_boto3/functional/test_s3.py

The response to a successful PUT or HEAD (or GET) of/on
an object matching any enabled lifecycle expiration rule should
include an x-amz-expiration header for the object.  The
x-amz-expiration header consists of an expiry-date, rule-id tuple
indicating the earliest matching rule and the corresponding
expiration date for the object.

boto3_s3tests: add tests for lifecycle expiration header

---

s3tests/functional/test_s3.py

Signed-off-by: zhang Shaowen <zhangshaowen@cmss.chinamobile.com>

Add test case for appending object.

---

s3tests_boto3/functional/__init__.py
s3tests_boto3/functional/test_s3.py

@cbodley is there anything else you'd want to add to this? I like it more than https://github.com/ceph/s3-tests/pull/252

Wip boto3 ssl

---

s3tests/functional/test_s3.py

http://tracker.ceph.com/issues/38811
Signed-off-by: Tianshan Qu <tianshan@xsky.com>

add case test for read not exist null version

---

s3tests_boto3/functional/test_s3.py

Add missing attributes for versioning

---

s3tests_boto3/functional/test_s3.py

Signed-off-by: chang liu <liuchang0812@gmail.com>

rgw: bucket tagging test

---

s3tests_boto3/functional/test_s3.py

test case for https://github.com/ceph/ceph/pull/25498

test versioned copy with urlencoded keys

---

s3tests_boto3/functional/test_s3.py

This is the test cases for https://github.com/ceph/ceph/pull/26538
Signed-off-by: zhang Shaowen <zhangshaowen@cmss.chinamobile.com>

add test cases for object lock.

---

s3tests_boto3/functional/test_s3.py

Adding test cases for keycount, delimiter, prefix

Listobjectsv2 testcases

---

s3tests_boto3/functional/test_s3.py

Adds tests for range headers that are not properly formatted (i.e. are
not of the form bytes=0-1024).

Add a test for an improperly formatted range.

---

s3tests_boto3/functional/test_s3.py

This is for https://github.com/ceph/ceph/pull/28988
Signed-off-by: zhang Shaowen <zhangshaowen@cmss.chinamobile.com>

Add a test case for continuation token in list objects v2

---

s3tests_boto3/functional/test_s3.py

References #72.
Signed-off-by: Andrew Gaul andrew@gaul.org

Test copy if-match and if-none-match

---

s3tests_boto3/functional/test_s3.py

Signed-off-by: Tianshan Qu <tianshan@xsky.com>

add test case for list with delimiter not skip special keys

---

s3tests_boto3/functional/test_s3.py

As per amazon s3 spec -
https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-s3-bucket-naming-requirements.html
The s3 bucket names should not contain upper case letters or underscore.
Name cannot end with dash or have consecutive periods, or dashes adjacent to periods
Name length shouldn't exceed 63 characters.
These rules are being enforced via
- https://github.com/ceph/ceph/pull/26787
This patch is to update the respective testcases as well.
Note: check_invalid_bucket_name() seems to have been broken. It should
try to create bucket using invalid name. Have addressed it in this
patch. Because of this few testcases (which were incorrectly passing
earlier) are failing in validate_bucket_name. Have marked them
'fails_on_rgw' as done for …

Fix create_bucket tests as per new bucket naming conventions

---

s3tests_boto3/functional/__init__.py
s3tests_boto3/functional/test_s3.py

As requested from @alimaredia , pushing #306 for merge into master branch.

Push #306 to master branch.

---

s3tests_boto3/functional/test_s3.py

NextContinuationToken is not cleartext, and we shouldn't assume that.
Also, the test should use it for ContinuationToken

Fix validate_bucket_listv2

---

s3tests/functional/test_s3_website.py

Do not run website tests when server emits 501

---

s3tests_boto3/functional/test_s3.py

Test reading an unreadable object

---

bootstrap

Signed-off-by: Ali Maredia <amaredia@redhat.com>

Minor fix to Centos 8 bootstrap changes

---

bootstrap

bootstrap: different packages for 'which'

---

s3tests_boto3/functional/test_s3.py

Fixes: https://tracker.ceph.com/issues/41870

list-objects: add basic tests for encoding

---

s3tests_boto3/functional/__init__.py
s3tests_boto3/functional/test_s3.py

iam: add a very basic user policy smoke test

---

s3tests_boto3/functional/__init__.py
s3tests_boto3/functional/test_s3.py

tests for https://github.com/ceph/ceph/pull/30033

Public buckets

---

s3tests_boto3/functional/__init__.py
s3tests_boto3/functional/test_s3.py

Ceph master public buckets backport

---

bootstrap
requirements.txt

Fixes: https://tracker.ceph.com/issues/45691
Signed-off-by: Kefu Chai <kchai@redhat.com>

bootstrap,requirements.txt: bump up setuptools and requests

---

s3tests_boto3/functional/test_s3select.py

Signed-off-by: gal salomon <gal.salomon@gmail.com>

add filter for s3select tests

---

README.rst
s3tests.conf.SAMPLE
s3tests_boto3/functional/__init__.py
s3tests_boto3/functional/test_sts.py

STS Tests Files and modification in __init__.py

---

s3tests_boto3/functional/test_s3.py

Test for: https://github.com/ceph/ceph/pull/37396
Signed-off-by: 胡玮文 <huww98@outlook.com>

Test list_objects_v2 KeyCount with Delimiter

---

s3tests_boto3/functional/test_sts.py

STS issue fix (https://tracker.ceph.com/issues/47588)

---

s3tests_boto3/functional/test_s3.py

test cases for https://tracker.ceph.com/issues/47028

test bucket recreation with different acls

---

s3tests_boto3/functional/test_s3.py

Signed-off-by: Or Friedmann <ofriedma@redhat.com>

Test expiration header for lc rules with tags

---

s3tests_boto3/functional/test_s3select.py

Signed-off-by: Albin Antony <aantony@redhat.com>

s3select predicate tests

---

README.rst
s3tests.conf.SAMPLE
s3tests_boto3/functional/__init__.py
s3tests_boto3/functional/test_sts.py

1. Webidentity test added to test_sts.py and required changes in __init__.py for the same.
2. Get session token issue resolution change (https://tracker.ceph.com/issues/47588).

Webidentity Test addition to test_sts.py

---

s3tests_boto3/functional/test_s3select.py

Signed-off-by: Albin Antony <aantony@redhat.com>

s3select tests for coalesce and case

---

s3tests/functional/test_s3_website.py

Related to https://github.com/ceph/ceph/pull/37914
Signed-off-by: Ilsoo Byun <ilsoobyun@linecorp.com>

Check if invalid payload is added after serving errordoc

---

s3tests_boto3/functional/test_s3.py

Signed-off-by: Or Friedmann <ofriedma@redhat.com>

Add test for GetUsage api

---

s3tests_boto3/functional/test_s3select.py

Signed-off-by: galsalomon66 <gal.salomon@gmail.com>

rename charlength and character_length function names

---

s3tests_boto3/functional/test_s3select.py

Signed-off-by: galsalomon66 <gal.salomon@gmail.com>

change test_s3select.py permission; add s3select attribute

---

s3tests_boto3/functional/test_s3select.py

Fix when then, date functions and NULL
Signed-off-by: Albin Antony <aantony@redhat.com>

s3select: align s3-tests with new changes in s3select

---

s3tests_boto3/functional/test_s3.py

test multipart upload with bucket policy
Signed-off-by: Or Friedmann <ofriedma@redhat.com>

test multipart upload with bucket policy

---

s3tests_boto3/functional/test_s3.py

Signed-off-by: Danny Abukalam <danny@softiron.com>

Add test to check retain date is in iso 8601 format

---

s3tests.conf.SAMPLE
s3tests_boto3/functional/__init__.py
s3tests_boto3/functional/test_sts.py

sts: Addition of new STS tests

---

s3tests.conf.SAMPLE
s3tests_boto3/functional/__init__.py

Signed-off-by: Ali Maredia <amaredia@redhat.com>

Disable ssl verify by default

---

s3tests_boto3/functional/test_s3.py

after the 1st successfull one should also return 200 OK
related tracker issue: https://tracker.ceph.com/issues/50141
related pr: https://github.com/ceph/ceph/pull/40594
Signed-off-by: Mark Kogan <mkogan@redhat.com>

test extra complete_multipart_upload()

---

s3tests.conf.SAMPLE
s3tests_boto3/functional/__init__.py
s3tests_boto3/functional/test_sts.py

New STS tests for ABAC related changes.

rgw sts abac tests

---

s3tests_boto3/functional/test_s3.py

- Adds tests for checking key limit (1000) in ``delete_objects()``.
@robbat2 @alimaredia

rgw/s3_boto3:Adds new delete_objects tests 

---

s3tests_boto3/functional/test_s3.py

new test case test_list_multipart_upload_owner() uses two different users to initiate multipart uploads, then tests that list_multipart_uploads() shows the correct user ids and display names for each upload

check Owner/Initiator fields of ListMultipartUploads response

---

bootstrap
requirements.txt
s3tests_boto3/functional/test_s3select.py

s3select tests are align with https://github.com/ceph/ceph/pull/40802
Signed-off-by: gal salomon <gal.salomon@gmail.com>

parquet tests

---

s3tests_boto3/functional/test_sts.py

s3tests_boto3/test_sts: Changing code for proper cleanup

---

s3tests_boto3/functional/test_s3.py

Adjust lc wait time to fix few spurious failures reported -
https://github.com/ceph/ceph/pull/40703#issuecomment-1060811704
http://qa-proxy.ceph.com/teuthology/mbenjamin-2022-02-23_15:42:19-rgw-wip-rgwlc-noreset-distro-basic-smithi/6703349/teuthology.log

lifecycle: Addressing lc spurious failures

---

s3tests/functional/test_s3.py
s3tests_boto3/functional/test_s3.py

This is a set of commits to add testing support for sse-s3 functionality in https://github.com/ceph/ceph/pull/44494
There's currently one problem here, the sse-s3 tests should not be run when vault is not deployed.  There needs to be logic here or in ceph to make that happen, which doesn't exist yet.

changes for sse s3.

---

s3tests_boto3/functional/test_s3.py

Adjust wait time for cloud-transition tests

Adjust wait time for cloud-transition test failures

---

s3tests_boto3/functional/test_s3.py

Mark the newly added sse* tests with 'fails_on_dbstore' attr

Tag sse* tests with 'fails_on_dbstore' attr

---

s3tests_boto3/functional/test_s3.py

related to https://tracker.ceph.com/issues/55460

fix GetBucketTagging error code

---

s3tests_boto3/functional/test_s3.py

Reproduces: https://tracker.ceph.com/issues/55766
Signed-off by: Igor Fedotov <igor.fedotov@croit.io>

Test case for locked and "marked-deleted" object version removal

---

s3tests.conf.SAMPLE
s3tests_boto3/functional/__init__.py
s3tests_boto3/functional/test_s3.py

Backport lifecycle expiration test updates to ceph-pacific branch

Ceph pacific lifecycle expiration fixes

---

s3tests_boto3/functional/test_headers.py
s3tests_boto3/functional/test_s3.py

Tag/Untag testcases failing on dbstore as per latest run against main

dbstore: Update the tests marked 'fails_on_dbstore'

---

s3tests_boto3/functional/test_s3.py

Fixes: https://tracker.ceph.com/issues/57401

cloud-transition: Adjust lc wait time

---

s3tests_boto3/functional/test_s3select.py

the upgraded CSV parser has some impact on engine result. (redundant comma, quote behavior)
Signed-off-by: galsalomon66 <gal.salomon@gmail.com>

new CSV parser has some impact on engine results

---

s3tests_boto3/functional/test_s3.py

If all of the following are true `ERR_TOO_SMALL` is wrongly returned:
- the bufferlist contains multiple items
- the last item has non-zero length
- that length is smaller than the POST Policy
The check should be `(ofs < min_len)` instead of `(len < min_len)`.
This is further confirmed by the fact that the next line does `s->obj_size = ofs`;
The bug was refactored in 2016, but was introduced in Oct 2012, when
this functionality was first added to RGW in commit 7bb3504d3f0974e9863f536e9af0ce8889d6888f.
Reference: https://github.com/ceph/ceph/blob/933a42f9af349b3b222270e7f19f1fe151d89e8e/src/rgw/rgw_op.cc#L4474-L4513
Reference: https://github.com/ceph/ceph/commit/7bb3504d3f0974e9863f536e9af0ce8889d6888f
Signed-off-by: Robin H. Johnson <rjohnson@digitalocean.com>

test_post_object_upload_size_below_minimum_rgw_max_chunk_size: new testcase for size validation bug

---

README.rst
s3tests_boto3/functional/test_sts.py

aslo, give more accurate instruction on how to run the tests
Signed-off-by: Yuval Lifshitz <ylifshit@redhat.com>

better error handling in the STS tests

---

s3tests_boto3/functional/test_iam.py

Fixes: https://tracker.ceph.com/issues/58762

iam: add back missing fails_on_dbstore tags

---

s3tests_boto3/functional/test_s3.py

when the tests were converted from boto2, they were rewritten as loops over `client.delete_object()`. switch back to multi-delete
the `test_versioning_multi_object_delete_with_marker_create` test case now checks the `delete_objects()` response, and uncovered the rgw bug https://tracker.ceph.com/issues/59048

boto3: multi-object-delete tests use client.delete_objects()

---

s3tests_boto3/functional/test_s3.py

Before the RGW fix PR was responding with 411 instead of 200
RGW fix PR: https://github.com/ceph/ceph/pull/50235

Test object PUT with chunked transfer encoding

---

s3tests_boto3/functional/test_s3select.py

- adding tests per JSON input types, which includes various SQL operators. 
- alignment of some of the test routines upon removing the XML tags(\<Payload\>\<Records\>\<Payload\>) from the s3select results.

Json s3tests

---

s3tests_boto3/functional/test_s3.py

Tests that concurrent multi-object delete requests which specify
the same versioned object instances return successful object
responses within response body.
relates to: https://tracker.ceph.com/issues/56646
Signed-off-by: Cory Snyder <csnyder@iland.com>

Add test_versioning_concurrent_multi_object_delete

---

s3tests_boto3/functional/test_s3select.py

merging #488 
(@alphaprinz PR)

Using get bucket name

---

s3tests_boto3/functional/test_s3.py

Related: https://tracker.ceph.com/issues/62033

Add test to verify HTTP OPTIONS on presigned URL

---

s3tests_boto3/functional/test_s3.py

for validating the fix of https://tracker.ceph.com/issues/62013

lc: test transition of plain null version

---

s3tests_boto3/functional/test_s3.py

test case for https://tracker.ceph.com/issues/63004
based on the [s3-tests.patch](https://tracker.ceph.com/attachments/download/6661/s3-tests.patch) provided with the bug report, but with the `bucket` field added to the payload (thanks Nicolas Lindae)

add test_post_object_wrong_bucket() for CVE-2023-43040

---

s3tests_boto3/functional/test_s3.py

for testing work in progress at https://github.com/ceph/ceph/pull/50148

test Head/GetObject on completed multipart parts

---

s3tests_boto3/functional/test_s3.py

test case for https://tracker.ceph.com/issues/45736

304 Not Modified tests still expect etag header

---

s3tests_boto3/functional/test_s3.py

add test case test_versioning_obj_suspended_copy() for https://tracker.ceph.com/issues/64340 
Signed-off-by: Jane Zhu [jzhu116@bloomberg.net](mailto:jzhu116@bloomberg.net)

add test case for object copy in versioning suspended bucket

---

s3tests_boto3/functional/policy.py
s3tests_boto3/functional/test_s3.py

* Test access deny via bucket policy
* Test 404 on no block configuration
Refs: https://github.com/ceph/ceph/pull/55652

BucketPublicAccessBlock: compatibility issues

---

s3tests_boto3/functional/test_s3.py

test cases for https://github.com/ceph/ceph/pull/54767 / https://tracker.ceph.com/issues/63724

s3: object lock tests for deletion of multipart objects

---

s3tests/functional/test_headers.py

with pytest 8.1.1, the setup/teardown functions no longer appear to run. replace them with a pytest fixture
Fixes: https://tracker.ceph.com/issues/64822

test_headers: use fixture to hook request headers

---

s3tests_boto3/functional/test_s3select.py

add handling for a new exception

Fix non handled error response

---

s3tests_boto3/functional/test_s3.py

Ref. https://github.com/ceph/ceph/pull/58686

BucketPolicy: donot allow NotPrincipal with Allow Effect

---

s3tests_boto3/functional/test_s3.py

Ref. https://github.com/ceph/ceph/pull/58689

BucketPolicy: add test for sse-c in conditions

---

s3tests_boto3/functional/test_s3select.py

ref. https://github.com/ceph/ceph/pull/56864

s3select: align error codes with the new AWS format

---

s3tests_boto3/functional/test_s3.py

Ref: https://github.com/ceph/ceph/pull/59253

UploadPartCopy: add test for source bucket with policy

---

s3tests_boto3/functional/test_iam.py

and update_thumbprint_for oidc_provider.

rgw: adding tests for add_client_id_to_oidc_provider

---

s3tests_boto3/functional/test_s3select.py

#579 had conflicts with ceph-master.

Fix cherry pick tracker 65651

---

s3tests_boto3/functional/test_s3.py

Refs: https://github.com/ceph/ceph/pull/56756

HeadBucket: add read-stats query string for usage test

---

s3tests_boto3/functional/test_s3.py

as well as test for object key filters

rgw/logging: tests for flush API

---

s3tests_boto3/functional/test_s3.py

add test case test_lifecycle_deletemarker_expiration_with_days_tag() for https://tracker.ceph.com/issues/63995
Signed-off-by: Jane Zhu [jzhu116@bloomberg.net](mailto:jzhu116@bloomberg.net)

add test case for delete-marker expiration with 'Days' tag

---

s3tests_boto3/functional/test_s3.py

PR : https://github.com/ceph/ceph/pull/61465

RGW:test-case to fix obj by multipart upload cant get tag

---

s3tests_boto3/functional/test_iam.py

PR https://github.com/ceph/ceph/pull/61853

rgw/iam: add RemoveClientIDFromOpenIDConnectProvider

---

s3tests_boto3/functional/test_s3.py

test case for https://github.com/ceph/ceph/pull/61946

s3: test that object lock can be enabled on an existing bucket

---

s3tests_boto3/functional/test_s3.py

Add testcase for [PR#60491](https://github.com/ceph/ceph/pull/60491)

cloud-restore:  Add testcase for restoring non-current versioned objects

---

s3tests_boto3/functional/test_s3select.py

This reverts commit 367075d28e52cd91167332b4c66f7299d8dd52d6.
This is a test to see if it is responsible for the failures in squid.

Revert "squid is missing exception handling, it cause s3-tests to fail"

---

s3tests_boto3/functional/test_s3.py

test case for https://tracker.ceph.com/issues/70191

s3: test bucket policy evaluation for CreateMultipartUpload

---

s3tests_boto3/functional/test_s3.py

This is for https://github.com/ceph/ceph/pull/54957, to test stacked delete markers.

add test case for stacked delete-markers

---

s3tests_boto3/functional/test_s3.py

Fixes: https://tracker.ceph.com/issues/69411

rgw/cloud-transition: increase time out for test cases

---

s3tests_boto3/functional/test_s3.py

Check the allow_read_through values for cases test_lifecycle_cloud_transition and test_read_through

rgw/s3tests: handle allow read through values in cloud transitions cases

---

s3tests_boto3/functional/test_s3.py

test coverage for https://tracker.ceph.com/issues/71083

add test coverage for DeleteBucketLifecycle

---

s3tests_boto3/functional/test_s3.py

Fixes: https://tracker.ceph.com/issues/71348

increase time out for restore op in test_restore_object_permanent

---

s3tests_boto3/functional/test_s3.py

when using API call to flush the pending logging object of the bucket, the flshed object name is returned.
tests were added to verify the right name is returned.

rgw/logging: add tests for flushed object name

---

s3tests_boto3/functional/test_s3.py

this test is used to verify: 
https://github.com/ceph/ceph/pull/63244
https://github.com/ceph/ceph/pull/63268

rgw/logging: test mpu complete in standard mode

---

s3tests_boto3/functional/test_s3.py

Adds a test to check the value of the AuthType field.

bucket-logging: test the AuthType log field

---

s3tests_boto3/functional/test_s3.py

test case for https://github.com/ceph/ceph/pull/64742

s3: test list_buckets with MaxBuckets/ContinuationToken

---

s3tests_boto3/functional/test_s3.py

testing: https://github.com/ceph/ceph/pull/65494

rgw/logging: verify error message when AccessDenied on target

---

s3tests_boto3/functional/test_s3.py

Fixes: https://tracker.ceph.com/issues/73010

rgw/logging: ceph master backports 3
