requirements.txt, s3tests/functional/test_s3.py
Since we fixed the rgw redirect code, it turns out that boto actually
follows on them. We just want to check if redirect is sent.
Signed-off-by: Yehuda Sadeh <yehuda@inktank.com>
=> s3tests: send raw http requests to test redirects

s3tests/functional/test_headers.py, s3tests/functional/test_s3.py
Disable these 2 tests that are currently failing in DHO:
s3tests.functional.test_headers.test_object_create_bad_contentlength_mismatch_above
s3tests.functional.test_s3.test_cors_origin_response
=> disable 2 tests that currently fail in DHO

s3tests/functional/test_s3.py
Previously test_bucket_create_naming_good_long_251 and
test_bucket_list_long_name could fail with BucketAlreadyOwnedByYou.
=> Call get_new_bucket_name in long bucket name tests

s3tests/functional/test_headers.py
Previously test_object_create_bad_contentlength_mismatch_above failed
with:
```
Traceback (most recent call last):
File "/home/gaul/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
self.test(*self.arg)
File "/home/gaul/work/s3-tests/s3tests/functional/test_headers.py", line 343, in test_object_create_bad_contentlength_mismatch_above
e = assert_raises(boto.exception.S3ResponseError, key.set_contents_from_string, content)
File "/home/gaul/work/s3-tests/s3tests/functional/utils.py", line 11, in assert_raises
callableObj(*args, **kwargs)
File "/home/gaul/work/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1379, in set_contents_from_string
encrypt_key=encrypt_key)
File …
```
=> Disable retries to test short writes

s3tests/functional/test_headers.py
S3 uses BadDigest for the former and InvalidDigest for the latter.
=> Test to find mismatched MD5

s3tests/functional/test_headers.py
This matches test_bucket_create_bad_contentlength_negative.
=> Do not check error_code with empty content length

s3tests/functional/test_s3.py
This commit allows test_bucket_head test_bucket_head,
test_bucket_head_extended, test_multipart_upload, and 
test_abort_multipart_upload to succeed against AWS-S3.  Also use 
public buckets for head tests since they do not require private
buckets.
=> Do not rely on Ceph extensions in head bucket

s3tests/functional/test_s3.py
mod_proxy_fcgi only has partial 100 continue support so we want to skip this test when testing against it.
Signed-off-by: Andrew Schoen <aschoen@redhat.com>
=> Add fails_on_mod_proxy_fcgi to functional.test_s3.test_100_continue

s3tests/functional/test_s3.py
Also set user metadata during put instead of issuing an additional
copy.
=> Replace and retain Content-Type in copy tests

s3tests/functional/test_s3.py
This mirrors test_bucket_acl_canned_during_create.
=> Add test_object_acl_canned_during_create

s3tests/functional/__init__.py
Some S3 implementations do not support object versioning - fall back
to listing without versions.
=> Fall back when nuking buckets

bootstrap
If RPM or DEB packages are missing, don't print to STDERR and bail. Instead, assume that the user has sudo rights, and attempt to install the missing packages for the user automatically.
CC'ing @andrewgaul in case he wants to review.
=> bootstrap: apt/yum install the list of dependencies

s3tests/functional/test_s3.py
User should be able to copy non-owned objects inside non-owned buckets when
they have full permissions to both bucket and object.
Test for issue #11639
=> s3tests: Test copying foreign object in foreign bucket

s3tests/functional/test_s3.py
Test does not consume obj_count or bytes_used and this function now
returns a dict of optional headers.
=> Remove unneeded called to _head_bucket

README.rst
That case doesn't exist any more. And I change it to a workable one.
Signed-off-by: tobe <tobeg3oogle@gmail.com>
=> Fix the example which is deprecated in README.rst

s3tests/functional/test_s3.py
Add multipart uploads copy part feature tests.
See https://github.com/ceph/ceph/pull/5673
=> Test multipart copy part feature

s3tests/functional/test_headers.py, s3tests/functional/test_s3.py
This patchset adds AWS4 auth testing support.
=> rgw: add AWS4 auth testing support

s3tests/functional/test_s3.py
AWS S3 has two behaviors for recreating a bucket depending if you use
the us-standard or another region:
```
>>> bucket = conn.create_bucket('gaul-default', location=Location.DEFAULT)
>>> bucket = conn.create_bucket('gaul-default', location=Location.DEFAULT)
>>> bucket = conn.create_bucket('gaul-uswest', location=Location.USWest)
>>> bucket = conn.create_bucket('gaul-uswest', location=Location.USWest)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib/python2.7/dist-packages/boto/s3/connection.py", line 499, in create_bucket
response.status, response.reason, body)
boto.exception.S3CreateError: S3CreateError: 409 Conflict
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>BucketAlreadyOwnedByYou</Code><Message>Your previous request to create the named …
```
=> Handle idempotent and BucketAlreadyOwnedByYou

s3tests/functional/test_s3.py
This has a different behavior than when the blob does not end with the
delimiter.
=> Test listing a blob which ends with delimiter

s3tests/functional/test_s3.py
`test_bucket_create_special_key_names` duplicates this test.  Add
missing cases and reformat for clarity.
=> Consolidate test_object_create_special_characters

s3tests/functional/test_s3.py
Issue #11563 deals with the COPY command breaking the Content-Type
header. Add a test case for this to ensure it remains fixed.
Reference: http://tracker.ceph.com/issues/11563
Signed-off-by: Robin H. Johnson <robin.johnson@dreamhost.com>
=> Add test for COPY Content-Type header

s3tests/functional/__init__.py
Bucket cleanup code was exiting after the first succesful bucket
removed, instead of cleaning up all buckets. This left many buckets
behind over time, causing large slowdowns of the test suite.
This was introduced in commit c41ebab9cf93617f06084cf88c297188b4aa9f67,
when changes for versioned files were added.
Signed-off-by: Kobi Laredo <kobi.laredo@dreamhost.com>
Signed-off-by: Robin H. Johnson <robin.johnson@dreamhost.com>
Backport: hammer
=> s3tests: do not exit cleanup after first bucket!

s3tests/functional/test_headers.py, s3tests/functional/test_s3.py
If you are run the S3 testsuite against a reverse proxy (eg haproxy)
rather than RGW directly, some of the tests will return errors from the
proxy, rather than haproxy itself.
Some proxies differ from RGW in the exact case of 'Bad Request', so do
the match in a case-insensitive manner. Haproxy for example returns 'Bad
request'.
This removes the need for some of the prior fails_on_dho test tags, as
the failure was due to haproxy.
Signed-off-by: Robin H. Johnson <robin.johnson@dreamhost.com>
=> Improve proxy error support: "Bad Request" case

s3tests/functional/test_s3.py
It works on civetweb, fails on apache.  Revert this once it is fixed.
See http://tracker.ceph.com/issues/15460
Signed-off-by: Sage Weil <sage@redhat.com>
=> test_s3: mark test_oject_head_zero_bytes fails_on_rgw

requirements.txt, s3tests/readwrite.py, s3tests/roundtrip.py, setup.py
There are some DNS resolving issue on 0.13.6.
Bumping to 1.0 fixes the issues for me.
Signed-off-by: Yuan Zhou <yuan.zhou@intel.com>
=> gevent: bump to >=1.0

requirements.txt, s3tests/common.py, s3tests/functional/__init__.py, s3tests/functional/test_s3.py, s3tests/functional/test_s3_website.py
This brings in almost all of the static website testsuite. It DOES detect if the website mode is available in the RGW instance before trying those tests (and otherwise skips the tests).
Also includes some needed refactoring, and annotations of further tests that fail on AWS.
Signed-off-by: Robin H. Johnson <robbat2@gentoo.org>
=> Static website testsuites

s3tests/functional/test_headers.py
Fix test cases:
* test_object_create_missing_signed_header_aws4
* test_object_create_missing_signed_custom_header_aws4
=> rgw: aws4: add test cases with missing signed headers

s3tests/functional/test_headers.py, s3tests/functional/test_s3.py
=> Annotate tests which create non-RFC2616 headers

s3tests/functional/test_s3.py
While it may be valuable to verify that deleting a non-existent key is OK, that doesn't seem to be the point of this test.
=> Complete multi-part upload during dry-run

s3tests/roundtrip.py
boto no longer rewind itself in set_contents_from_file, which will trigger the assert in
realistic/RandomContentFile::seek
Signed-off-by: Tianshan Qu tianshan@xsky.com
=> fix rgw_roundtrip test fail

bootstrap
python2-pip doesn't exist in rhel and python-virtualenv ships pip in its package.
Signed-off-by: Vasu Kulkarni <vasu@redhat.com>
=> remove python2 pip

s3tests/functional/test_s3.py
If we set object's ACL with no version id specified, the latest object's ACL should be changed. 
The bug fix is in https://github.com/ceph/ceph/pull/13078
Fixes: http://tracker.ceph.com/issues/18923
=> Add a test case for setting acl on object with no version id specified.

s3tests/functional/test_s3.py
According to https://tools.ietf.org/html/rfc7232
header 'If-Modified-Since' should be a correct HTTP-date.
For example: `Tue, 15 Nov 1994 12:45:26 GMT`;
not `1994-11-15T12:45:26.000Z`.
=> Fix 'If-Modified-Since' format string

README.rst, config.yaml.SAMPLE, s3tests/functional/__init__.py, s3tests/functional/test_s3.py
this is the same as https://github.com/ceph/s3-tests/pull/118, except it's been rebased and includes a fix for some HEAD requests that now require a customer key header
=> functional tests for server side encryption

s3tests/functional/test_s3.py
https://github.com/ceph/ceph/pull/14117 added the `x-amz-version-id` header to GetObj requests. boto's [Key.get_contents_as_string()](http://boto.cloudhackers.com/en/latest/ref/s3.html#boto.s3.key.Key.get_contents_as_string) will set `Key.version_id` based on this header. this is causing `test_versioning_obj_plain_null_version_overwrite()` to issue a `get_contents_as_string()` against the version_id it had just deleted, failing with `S3ResponseError: 404 Not Found`
=> clear key.version_id now that GET requests return x-amz-version-id header

s3tests/functional/test_s3.py
Because https://github.com/ceph/ceph/pull/15677 fixes the bug and lifecycle doesn't process the bucket which has been deleted now. The sleep time should be lower in lifecycle expiration so that the test case can pass(lc interval is still 2 seconds).
=> modify the thread sleep time in lifecycle expiration test so that it can pass on ceph master branch.

s3tests/functional/test_s3.py
Added test cases for LC policies with no ID in xml, no prefix and an
empty and non empty Filter.
=> lifecycle: add test cases using filter & no id

s3tests/functional/test_s3.py
Allows us to temporarily filter out tests based on timing attribute
which currently fail in the teuthology runs
=> lc: set attribute as lifecycle_time for lc tests using timing ops

s3tests/functional/test_s3.py
Earlier values expected a lc debug interval of 2s, which is a pretty
short time window and can often lead to failures if the processing
didn't complete within the next day. This commit assumes the currently
configured LC debug interval of 10s (which is already used in vstart and teuthology yamls), 
and gives time intervals using the following logic:
Worst case:
LC start-time : 00:00
obj upload    : 00:01
LC run1       : 00:10 -> object not expired as it is only 9s old
LC run2       : 00:20 -> object will expire in this run, however we
can't exactly guess when this run will complete, for a moderate amount
of objects this can take anywhere between 1 to a max of 10s, let us give
it a wiggle room to complete around 8s, given the amount of objects in a
teuthology run, it should be mostly …
=> lc: Give more flexibility for LC expiration times

s3tests/functional/test_s3.py
Some tests, like test_object_header_acl_grants and test_bucket_header_acl_grants, use the same id for all permissions. `sort()` is stable, so those tests end up testing the order of acl grants returned by Boto. Not sure, but I think this may in turn depend on the order of HTTP headers, where the order is not significant.
=> Care less about ordering when checking grants

s3tests/functional/test_s3.py
https://github.com/ceph/ceph/pull/17882 changes the result of sse operations that don't provide all of the necessary headers - they now fail with 400 Bad Request instead of silently disabling encryption
=> expect 400 for missing sse headers

s3tests/functional/test_s3.py
test for https://github.com/ceph/ceph/pull/17934
Signed-off-by: yuliyang <yuliyang@cmss.chinamobile.com>
=> test for https://github.com/ceph/ceph/pull/17934

s3tests/functional/test_s3.py
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1501005
Also needs backport to ceph-luminous.
Signed-off-by: Vasu Kulkarni <vasu@redhat.com>
=> Check for either 400 or 416 response code for invalid range test

s3tests/functional/test_s3.py
1. According to the commit 9204283def8e0bcfe14a57f0c87ed20735214f53,
lc debug interval should be set to 10s.
2. Cleanup some unneeded comments.
Signed-off-by: Enming Zhang <enming.zhang@umcloud.com>
=> Fix a typos for lifecycle test case

s3tests/functional/policy.py, s3tests/functional/test_s3.py, s3tests/functional/utils.py
Adding tests for bucket policies with conditionals
Tests added so far:
- Get Object (with ExistingObjectTag)
- Put Object Tagging
- Get Object Tagging 
- Put Object
- Put Object ACL
- Get Object ACL
- CreateBucket
- ListBucket (with prefix/max-keys/delimiter conditionals)
=> test bucket policy with conditionals 

s3tests/functional/test_s3.py
This pr is prepared for https://github.com/ceph/ceph/pull/20002.
=> Add test for muiltpart copy without 'x-amz-copy-source-range' header

requirements.txt, s3tests/functional/test_s3.py
the old requests library doesn't support recent versions of tls
=> unpin the requests library version

bootstrap
because gevent 1.3.2 requires cffi>=1.11.5, and cffi requires
libffi-dev to build.
Signed-off-by: Kefu Chai <kchai@redhat.com>
=> bootstrap: add libffi-dev for gevent

s3tests_boto3/functional/test_s3.py
The assumption that there may be only one rule per prefix has
been removed.  The rules specifically tested here--without tag
filters--do overlap but are not in conflict.
I am proposing to remove altogether rather than writing new
deconfliction logic.
=> boto{2,3}: rm functional.test_s3.test_lifecycle_rules_conflict

s3tests/functional/__init__.py, s3tests_boto3/functional/__init__.py
if a bucket delete request times out, the retry will likely get a 404 NoSuchBucket response. ignore that error and treat this as a success
this showed up as a failure in http://qa-proxy.ceph.com/teuthology/yuriw-2019-04-17_22:56:53-rgw-nautilus-distro-basic-smithi/3859872/teuthology.log
```
S3ResponseError: S3ResponseError: 404 Not Found
<?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchBucket</Code><BucketName>test-client.0-vkgr2clo531930f-92</BucketName><RequestId>tx000000000000000001818-005cb9a0bb-11f8-default</RequestId><HostId>11f8-default-default</HostId></Error>
```
where the boto log shows a retry on the final DELETE request:
```
boto: DEBUG: encountered SSLError exception, reconnecting
boto: DEBUG: establishing HTTPS connection: host=example.com, kwargs={'port': 7281, …
```
=> nuke_prefixed_buckets() ignores 404 from bucket delete

bootstrap
when running on fedora29 the virtualenv was python3. this didn't work since the tests are pyhton2.
Signed-off-by: Yuval Lifshitz <yuvalif@yahoo.com>
=> make sure that virtualenv is python2 regardless of host

bootstrap
Previously the aliases would install but subsequent runs would not
find the exact package name.  This caused yum to unnecessarily re-run.
=> Explicitly reference Fedora Python 2 dependency

s3tests_boto3/functional/test_s3.py
Signed-off-by: Albin Antony <aantony@redhat.com>
=> startafter and continuation token shouldn't  be returned if they are not specified in the request

s3tests_boto3/functional/test_s3.py
This is for https://github.com/ceph/ceph/pull/28587
Signed-off-by: zhang Shaowen <zhangshaowen@cmss.chinamobile.com>
=> Add a case for lifecycle expiration on versining enabled bucket.

s3tests/functional/test_s3.py
test_bucket_policy_different_tenant fails because it adds a : to the beginning of the hostname, ie:
> Host: :test-client.0-oktbnrjh6qacop7-25.s3.smithi003.front.sepia.ceph.com
the append tests fail with 403 Forbidden because they use `key.generate_url()` on a connection with calling_format=subdomain, but send the raw request to the unmodified hostname. because the Host header doesn't match the signature of the presigned url, the signature validation fails
=> boto2: tag more tests with fails_with_subdomain

s3tests_boto3/functional/test_s3.py
these changes accidentally merged to ceph-master in https://github.com/ceph/s3-tests/pull/285, so we need them on master too
=> Fix create_bucket tests as per new bucket naming conventions

s3tests_boto3/functional/__init__.py, s3tests_boto3/functional/test_s3.py
In this change I've tried to trade compatibility between current sse-kms barbican tasks and our feature implementation of https://github.com/ceph/ceph/pull/29783.
Because the way code is  structured* in current sse-kms implementation, s3_tests.py have an handful of duplicated tests which I have removed.
The side effect of it is that, until sse-kms change above is merged, tests for the "testing" sse-kms backend (the local one in the ceph.conf) will not be executed. 
However, all the sse-kms functional tests will run against the Barbican backend. This setup should allow us to run tests for Vault and at the same time not breaking compatibility with current code.
=> Passing sse-kms keys from configuration instead of hard coding in tests

bootstrap
Fixing bootstap for RHEL/Centos 8
- When VERSION_ID is less than 8, installing the python packages, otherwise installing the python2 packages.
- When we are using the python2-virtualenv, we will run virtualenv-2.
- Making sure we have which installed
Fixes #318
=> Fixing bootstap for RHEL/Centos 8

s3tests_boto3/functional/test_s3.py
Continue to require them in `test_bucket_head_extended`.  Only Ceph
supports these headers.
=> Ignore missing x-rgw-* headers

bootstrap
Use of declare that is bash specific was introduced in:
d44c923405e22ea8b6cc1ab4316be3cc07f29b5
=> bootstrap: switch to bash

s3tests_boto3/functional/test_s3.py
**According to ISSUE #317 :** 
The ceph test "test_put_obj_with_tags" contains the check:
eq(response['TagSet'], tagset).
it fails because of tagging order, but AWS spec does not specifies which order the tags supposed to return.
**CHANGES:**
1. sort both lists.
**FIXES**:
1. ISSUE #317
=> test_put_obj_with_tags 

bootstrap
Also reformatted the bootstrap script to parse /etc/os-release instead, so that
more distro/pkg manager support could be added at a later point in time and
fixed the error message
=> bootstrap: add support for *suse distributions

s3tests_boto3/functional/__init__.py
In the function of nuke_prefixed_buckets, if some err is thrown when deleting buckets, the left buckets remain uncleaned.
It is kind of resoruce leak on some charged platform. We have to clear them manually.
I know the original code is meant to give the user some hint by rasing error. But the resource leak of left buckets is a little annoying.
Signed-off-by: Pei <huangp0600@126.com>
=> Fix: Bucket resource leak when cleanup

bootstrap
this fails on Ubuntu 20.04:
> virtualenv: error: unrecognized arguments: --no-site-packages --distribute
according to `virtualenv -h`:
```
--no-site-packages    DEPRECATED. Retained only for backward compatibility.
Not having access to global site-packages is now the
default behavior.
--distribute          DEPRECATED. Retained only for backward compatibility.
This option has no effect.
```
=> bootstrap: remove deprecated virtualenv options

s3tests_boto3/functional/test_s3.py
Commit bf956df71e56bcdae7d41b9789d8e8d775f76007 adding
listobvjectsv2 tests inadvertently changed the v1
test_lifecycle_expiration test, which it had copied to
create a v2 version.  Revert this.
=> fix/restore test_lifecycle_expiration checks

s3tests/fuzz/headers.py
Currently, the test_expand_random_binary test fails on big-endian
systems.  It turns out that this is because the special_random
routine in RepeatExpandingFormatter uses struct.pack in a manner
where the returned byte sequence depends on host byte order.
Fixed this to enforce the same output across platforms.
Note that these tests were completely removed after nautilus, so I'm sending this PR only against the ceph-nautilus branch.   (We are still running Teuthology against Ceph nautilus, and this issue causes test failures there.)
=> [ceph-nautilus] Fix fuzzer test on big-endian systems

s3tests_boto3/functional/test_s3.py
n.b., RGW does not send a response document for this operation,
which seems consistent with
https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadBucket.html
=> Add test for HeadBucket on a non-existent bucket

s3tests_boto3/functional/test_sts.py
two test cases for HEAD on a nonexistent object: one where the assumed role policy allows s3:ListBucket, and where it denies
=> sts: test role policy around nonexistent objects

s3tests_boto3/functional/test_s3.py
- Adds lifecycle transition rule test for invalid iso8601 format specified in transition date attribute.
@alimaredia @robbat2
=> rgw/s3_boto3:Adds lifecycle transition tests

s3tests_boto3/functional/test_s3.py
Tests are added for GetBucketEncryption, PutBucketEncryption,
and DeleteBucketEncryption APIs.
Related PR: https://github.com/ceph/ceph/pull/42222
Signed-off-by: Rahul Dev Parashar <rahul.dev@flipkart.com>
=> rgw/s3_boto3: Add tests for bucket encryption APIs

s3tests_boto3/functional/test_s3.py
Tests to go along with https://github.com/ceph/ceph/pull/37933, which fixes an issue where multi-object delete didn't respect object locks.
=> Tests for multi-object delete with object lock

s3tests.conf.SAMPLE, s3tests_boto3/functional/__init__.py, s3tests_boto3/functional/test_s3.py
Closes: #274 
This PR introduces `ssl_verify` configurable which helps in disabling SSL certificate verification. We use self-signed certificates for our downstream testing hence this support allows to test RGW endpoint with SSL.
Signed-off-by: Pragadeeswaran Sathyanarayanan <psathyan@redhat.com>
=> Add support for disabling SSL certificate verification

s3tests_boto3/functional/__init__.py, s3tests_boto3/functional/test_s3.py
test cases for https://github.com/ceph/ceph/pull/42505
also reworks `nuke_prefixed_buckets()` to be aware of s3 object lock. some locked objects can't be deleted until their retention period expires, so each object lock test case should use a short retention period (~10 seconds), and `nuke_prefixed_buckets()` will wait up to 60 seconds to clean them up
=> object-lock: test changes between retention modes

README.rst
Run: S3TEST_CONF=your.conf ./virtualenv/bin/nosetests s3tests.functional.test_s3:test_bucket_list_empty
But get an error: "ERROR: Failure: ValueError (No such test test_bucket_list_empty)".
Because test_bucket_list_empty is a test case in s3tests_boto3 directory.
Signed-off-by: Liu Lan <liulan_yewu@cmss.chinamobile.com>
=> docs: fix wrong example in README.rst

s3tests_boto3/functional/test_s3select.py
PR contains tests of several PR's.
1. s3select-responses(progress,stats,end,cont) 
2. output-serialization different options
3. presto changes(table-alias, case-insensitive)
tests in this PR align with https://github.com/ceph/ceph/pull/42416
=> s3select-tests:  new-s3select-responses, output-serialization, presto alignments

s3tests_boto3/functional/test_s3.py
Signed-off-by: Pragadeeswaran Sathyanarayanan <psathyan@redhat.com>
When executing S3-tests against Red Hat Ceph Storage 5.0 or downstream development builds, we have observed the following test failures
```
s3tests_boto3.functional.test_s3.test_object_acl_canned_bucketownerread ... FAIL
s3tests_boto3.functional.test_s3.test_object_acl_canned_bucketownerfullcontrol ... FAIL
```
Our analysis of the issue indicated the problem to be with dictionaries being compared. At times, the position of actual and expected dictionaries are on different positions in the list. 
This PR attempts to improve the reliability of `check_grants` method to solve the failures.
__Error log__
http://magna002.ceph.redhat.com/ceph-qe-logs/psathyan/s3/5.0-nossl/s3_tests_0.log
__Logs__ …
=> Improving check_grants reliability

s3tests_boto3/functional/test_s3.py
Increase wait time in test_lifecycle_deletemarker_expiration(..) to avoid any spurious failure.
=> lifecycle/deletemarker_expiration: Increase timer window

s3tests/functional/test_s3.py
Signed-off-by: Pragadeeswaran Sathyanarayanan <psathyan@redhat.com>
We are seeing this failure when running against RHCS 4.3
```
======================================================================
FAIL: s3tests.functional.test_s3.test_versioning_obj_create_versions_remove_all
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/cephuser/s3-tests/venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
self.test(*self.arg)
File "/home/cephuser/s3-tests/s3tests/functional/test_s3.py", line 7148, in test_versioning_obj_create_versions_remove_all
_do_remove_versions(bucket, objname, 0, 5, 0.5, k, c)
File "/home/cephuser/s3-tests/s3tests/functional/test_s3.py", line 6862, in _do_remove_versions …
```
=> Fix versioning tests failures due multiple removal of object

s3tests/functional/test_headers.py, s3tests/functional/test_s3.py, s3tests/functional/test_s3_website.py, s3tests_boto3/functional/test_headers.py, s3tests_boto3/functional/test_s3.py, s3tests_boto3/functional/test_sts.py
To be able to successfully run s3tests on dbstore backend in teuthology, mark all the s3-tests currently failing on it with 'fails_on_dbstore' attr
=> Tag testcases failing on dbstore with 'fails_on_dbstore' attr

s3tests.conf.SAMPLE
fixes this error when trying to run against `s3tests.conf.SAMPLE`:
```
~/s3-tests $ S3TEST_CONF=s3tests.conf.SAMPLE virtualenv/bin/nosetests s3tests_boto3/functional/test_s3.py        
ERROR                                                                                                                                                         
======================================================================                                                                                        
ERROR: test suite for <module 's3tests_boto3.functional.test_s3' from 's3-tests/s3tests_boto3/functional/test_s3.py'>                           
----------------------------------------------------------------------
Traceback (most recent call last):
File …
```
=> s3tests.conf.SAMPLE: comment out [s3 cloud] section

README.rst, s3tests_boto3/functional/__init__.py, s3tests_boto3/functional/test_iam.py
Inline with the issue created at #448 , adding few put/get/list/delete User Policy Tests.
=> Contributing User Policy tests

s3tests_boto3/functional/test_iam.py
Newly added User policy tests (https://github.com/ceph/s3-tests/pull/453) are failing on dbstore with
error "Your config file is missing the "iam" section!"
For now tagged these tests as 'fails_on_dbstore' but these tests need to be made optional based on if iam section added or not in s3tests.conf (https://tracker.ceph.com/issues/56421)
Fixes: https://tracker.ceph.com/issues/56418
=> Fix User Policy test failures on dbstore

s3tests_boto3/functional/test_s3.py
Updated test_set_bucket_tagging test for verifying the http status code
for DeleteBucketTagging case.
Related CEPH PR: https://github.com/ceph/ceph/pull/47262
Signed-off-by: Shriya Deshmukh <shriya.deshmukh@seagate.com>
=> rgw/s3_boto3: Added http status code verification for DeleteBucketTagging case.

bootstrap
I tried running this inside rocky linux and it complained that it was not supported. Rocky in the EL family so I added the name there.
=> Add support for rocky linux in bootstrap

s3tests_boto3/functional/test_s3.py
i don't think any of our CopyObj test cases were large enough to have tail objects, so weren't exercising our tail object ref ounting strategy
=> add test_object_copy_16m to test refcounting of tail objects

requirements.txt
it looks like ubuntu 20.04 recently updated its botocore version, and introduced a regression in v2 signatures that causes 4 test failures: https://tracker.ceph.com/issues/58059
pin `botocore <1.28.0` in requirements.txt to avoid this regression
=> pin botocore to resolve v2 signature failures

s3tests_boto3/functional/test_s3.py
this has been failing consistently in local testing. test_sts.py has lots of user policy test coverage, so this test case in test_s3.py is superfluous
Fixes: https://tracker.ceph.com/issues/58365
=> test_s3: remove test_user_policy()

.gitignore, requirements.txt, tox.ini
- Fix tox.ini syntax
Modern tox versions require the expected environment variables to be listed one by one on separate lines in tox.ini
- Add `venv` to list of ignored names for git
This is a common name for a local Python virtual environment. Less typing than `virtualenv`
- Add `tox` to requirements.txt
Installing `tox` via `pip` has the advantage of including it in the virtual environment, thus avoiding trouble on operating systems shipping by default with python3.6 or older. It's also nice that `pip install -r requirements.txt` is now sufficient to set up the testing environment, after initializing the virtual environment with a moder-enough python version.
=> QoL: Fix tox.ini syntax and other minor things

s3tests_boto3/functional/__init__.py
=> boto3: list_versions() omits empty KeyMarker/VersionIdMarker

s3tests_boto3/functional/test_s3.py
Mark testcase "test_lifecycle_expiration_header_and_tags_head" as fails_on_dbstore
=> dbstore: add back missing 'fails_on_dbstore' tag

s3tests_boto3/functional/test_s3.py
Few checks were incorrectly mapped when switched to 'assert' (quincy -https://github.com/ceph/s3-tests/blob/ceph-quincy/s3tests_boto3/functional/test_s3.py#L9886). 
This commit fixes the same.
=> lifecycle: Fix test_lifecycle_expiration_header_* testcases

s3tests/functional/test_s3_website.py
this was added to [collections.abc](https://docs.python.org/3/library/collections.abc.html) in python 3.3, and removed from collections in 3.10
> AttributeError: module 'collections' has no attribute 'Container'
Fixes: https://tracker.ceph.com/issues/58960
=> s3website: collections.Container removed from python3.10

s3tests_boto3/functional/test_s3.py
there's a `test_sse_s3_default_multipart_upload` test case, but it wasn't verifying that the upload was actually encrypted
for https://github.com/ceph/ceph/pull/49409 https://tracker.ceph.com/issues/59218
=> test_sse_s3_default_multipart_upload verifies encryption header

README.rst
fix a copy/paste mistake pointed out in https://github.com/ceph/s3-tests/pull/482#discussion_r1226106436
=> readme: change fails_on_aws back to fails_on_rgw

s3tests_boto3/functional/test_s3select.py
S3Select tests uses hard-coded bucket name.
The teardown only deletes bucket with names that start with certain prefix, so the bucket created by these tests remain after test is complete.
Using get_new_bucket_name() instead will auto-delete the new bucket when a test is done.
Signed-off-by: Amit Prinz Setter <aprinzse@redhat.com>
=> Use get_new_bucket_name() in select tests.

s3tests_boto3/functional/test_s3.py
Object mtime should not change for any attr changes unless its a copy operation. 
Verify the same using PutObjectACL op.
Tracker: https://tracker.ceph.com/issues/61770
Fix: https://github.com/ceph/ceph/pull/52160
=> Add testcase to verify obj mtime post setattrs

s3tests_boto3/functional/test_s3.py
stop using `head_bucket()` to fetch these response headers, and use `list_objects_v2()` instead to count objects and sizes. this allows us to remove several `fails_on_aws` and `fails_on_dbstore` markers
Fixes: #315
=> remove reliance on x-rgw-object-count and x-rgw-bytes-used headers

README.rst
having the filter from previous examples might be confusing because It can be interpreted as a needed part to run only boto3 tests. I removed it to make the example as simple as possible
=> Remove filtering from boto3 test example for simplicity

s3tests_boto3/functional/test_s3.py
https://tracker.ceph.com/issues/63537 reported that large dates (with year after 2107) got truncated when written. test with a later date, and check that get_object_retention() gives back the date we put
=> object lock: test very large RetainUntilDate

s3tests_boto3/functional/test_s3.py
This improves the testing for presigned URLs for
both get_object and put_object when using
generate_presigned_url().
It covers the case where you pass for example
a x-amz-acl (ACL in params for generated_presigned_url) header that should be signed.
Tests the regression in [1].
[1] https://tracker.ceph.com/issues/64308
=> Add more testing for presigned URLs

s3tests_boto3/functional/test_s3.py
when the local timezone is not UTC and if it is a day behind, lifecycle_header tests fails with 2 days not equal to 1 so replacing datetime.now() with datetime.utcnow()
=> replace datetime.now with datetime.utcnow()

pytest.ini, s3tests.conf.SAMPLE, s3tests_boto3/functional/__init__.py, s3tests_boto3/functional/iam.py, s3tests_boto3/functional/test_iam.py, s3tests_boto3/functional/test_s3.py, s3tests_boto3/functional/test_sns.py
renames the `test_of_iam` label to `iam_tenant` for the existing tenant-based iam tests
adds new `[iam root]` and `[iam alt root]` config sections for account root users, and a new set of `iam_account` and `iam_cross_account` test cases that use them
adds pytest fixtures `iam_root` and `iam_alt_root` that return the corresponding boto client, with cleanup logic to nuke any created users/roles/etc. all iam resources created by the tests have names starting with `iam name prefix = s3-tests-` and paths starting with `iam path prefix = /s3-tests/` so this cleanup logic doesn't nuke anything else in the aws account
adds account-based test cases for the following iam api categories:
* User
* AccessKey
* UserPolicy
* Group
* GroupPolicy
* Role
* RolePolicy
* OpenIDConnectProvider
verified to …
=> iam: add tests for account-based IAM apis

s3tests_boto3/functional/test_s3.py
[ This pull request supersedes #437 ]
TestName:
s3tests_boto3.functional.test_s3:test_buckets_list_ctime
Problem:
The test creates 5 buckets for a user but in an assertion check, it asserts false if any bucket of the user has CreationTime less than a day prior to current time.
Due to this reason the test fails if the user has pre-existing buckets older than a day.
Solution:
Assert only on the CreationTime of buckets that were created with test execution.
=> Fix wrong assertion of the test: `test_buckets_list_ctime`

s3tests_boto3/functional/test_s3.py
test_multipart_get_part() tests 'normal' multipart uploads. add a new test case for a multipart upload with a single part to tests the fix for https://tracker.ceph.com/issues/66705 in https://github.com/ceph/ceph/pull/58288
=> test Get/HeadObject with partNumber for single-multipart upload

s3tests.conf.SAMPLE, s3tests_boto3/functional/__init__.py, s3tests_boto3/functional/test_s3.py
the before-call hook url-encodes the ':' part of tenanted bucket names to resolve SignatureDoesNotMatch errors
removed the list-v2 version of the test since it isn't relevant to bucket policy test coverage
add a new test case that creates the bucket under the tenanted user, then uses the main client to access it
=> s3: reenable tenanted bucket policy test

s3tests_boto3/functional/test_s3select.py
s3select tests use an assert on 2 statement results
the 2 statements have different syntax but should return the same results for the same input (its semantically equal).
upon an empty result on both statements, the test infrastructure failed on assert-false.
the PR changes this behavior, in case both are empty, its OK, with a warning message.
https://tracker.ceph.com/issues/65651
=> s3select: fix the assert per empty results

s3tests_boto3/functional/__init__.py, s3tests_boto3/functional/test_s3.py
This adds tests for get_object presigned URLs
using signature v2.
Also code formatting.
This change depends on [1].
[1] https://github.com/ceph/ceph/pull/59977
=> Add v2 signature presigned get_object tests

s3tests_boto3/functional/test_s3.py
Include noncurrent versioned objects with instance empty in lifecycle transition/expiration tests.
Ceph PR: https://github.com/ceph/ceph/pull/60157
Fixes: https://tracker.ceph.com/issues/68402
=> Updating lifecycle_noncur* tests to include objects with instance empty

s3tests_boto3/functional/test_s3.py
for 403 error code (and not specific errors) so that the tests pass for any order of auth engines.
=> rgw/s3tests: making the tests generic to check only

s3tests_boto3/functional/test_sts.py
this test fails if `rgw_s3_auth_order` puts local before sts, because the local engine will gladly accept the s3_main user's credentials
Fixes: https://tracker.ceph.com/issues/69001
=> sts: remove test_get_session_token_permanent_creds_denied

s3tests_boto3/functional/test_s3.py
By default quota is disable at user/bucket level.
if quota is disable then these value will not return so need to modify test_head_bucket_usages
```
'X-RGW-Quota-User-Size'
'X-RGW-Quota-User-Objects'
'X-RGW-Quota-Bucket-Size'
'X-RGW-Quota-Bucket-Objects'
```
to Fix: https://tracker.ceph.com/issues/68211
Signed-off-by: Raja Sharma <raja@ibm.com>
Tracker: https://tracker.ceph.com/issues/68211
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).
- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.
- When filling out the below checklist, …
=> rgw:modify testcase rgw header when bucket  or user quota is disabled

README.rst, pytest.ini, s3tests_boto3/functional/test_s3.py
bucket logging is implemented here:  https://github.com/ceph/ceph/pull/59808
~~https://github.com/ceph/ceph/pull/54815~~
=> rgw/logging: basic set of tests for bucket logging

s3tests_boto3/functional/test_s3.py
If the bucket is owned by a different account, the request fails with the HTTP status code 403 Forbidden (access denied).
PR : https://github.com/ceph/ceph/pull/61215
Fixes : https://tracker.ceph.com/issues/64526
=> rgw test-case to support x-expected-bucket-owner

requirements.txt, s3tests_boto3/functional/__init__.py, s3tests_boto3/functional/test_headers.py, s3tests_boto3/functional/test_iam.py, s3tests_boto3/functional/test_s3.py, s3tests_boto3/functional/test_sns.py
unpin botocore version and work through failures
disable failing sigv2 tests:
```
FAILED s3tests_boto3/functional/test_s3.py::test_cors_presigned_get_object_v2 - botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CreateBucket operation: None                                              
FAILED s3tests_boto3/functional/test_s3.py::test_cors_presigned_get_object_tenant_v2 - botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CreateBucket operation: None
FAILED s3tests_boto3/functional/test_s3.py::test_cors_presigned_put_object_v2 - botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CreateBucket operation: None                                              
FAILED …
```
=> unpin botocore, disable failing sigv2/checksum tests

s3tests_boto3/functional/test_s3.py
followup to https://github.com/ceph/s3-tests/pull/619, reenable range requests to test https://github.com/ceph/ceph/pull/61901
=> s3: reenable tests with range requests and checksums

pytest.ini, s3tests.conf.SAMPLE, s3tests_boto3/functional/__init__.py, s3tests_boto3/functional/test_s3.py
This tests are added to tests temporary restore, permanent restore and read through restore object functionality, this includes zonegroup parameters and checks.
Signed-off-by: shreyanshjain7174 <ssanchet@redhat.com>
=> rgw/restore: s3tests to test restore object functionality

s3tests_boto3/functional/__init__.py, s3tests_boto3/functional/test_s3.py
Refrence: https://github.com/ceph/ceph/pull/57629
=> BucketPolicy: add tests for ConfirmRemoveSelfBucketAccess header

s3tests_boto3/functional/test_s3.py
Ref. https://github.com/ceph/ceph/pull/57206
=> BucketPublicAccessBlock: add tests for RestrictPublicBuckets

s3tests_boto3/functional/test_s3.py
test_versioned_concurrent_object_create_concurrent_remove as the associated tracker is marked as resolved and the test also passes against main.
=> rgw/s3tests: removing fails_on_rgw for

s3tests/functional/test_s3_website.py
resolves error with recent pytest:
```
==================================== ERRORS ====================================
____________ ERROR collecting s3tests/functional/test_s3_website.py ____________
'yield' keyword is allowed in fixtures, but not in tests (test_routing_generator)
```
use https://docs.pytest.org/en/7.1.x/example/parametrize.html instead to generate a `test_routing_generator()` for each entry in `ROUTING_RULES_TESTS`
=> pytest: use parametrize for s3website test_routing_generator()

s3tests_boto3/functional/test_s3.py
verify that the names of the log objects in the log bucket are lexicographically ordered.
this is test for: https://github.com/ceph/ceph/pull/63264
=> rgw/logging: test log object name order

s3tests_boto3/functional/test_s3.py
this is teuthology passing of these tests when running inside `master` agains ceph `main`:
https://pulpito.ceph.com/yuvalif-2025-06-25_08:17:43-rgw:bucket-logging-main-distro-default-smithi/
(no run of this work as part of `ceph-master` against ceph `main`)
=> rgw/logging: ceph-master backports

README.rst
Fixed typos in the example commands.
=> readme: fix typo

pytest.ini, s3tests_boto3/functional/test_s3.py
test coverage for https://github.com/ceph/ceph/pull/63348
put_object tests are duplicated to test non-versioned and overwrites of a current version
delete_object(s) tests are duplicated to test non-versioned, deletes of a current version, and deletes of a specific version
=> s3: test conditional put_object() and delete_object()

s3tests_boto3/functional/test_s3.py
This is the test-case for https://github.com/ceph/ceph/pull/64804. 
If the `restoe-object` request is re-issued on a cloud-restored object, it should update restoration period accordingly from the time the request is re-issued.
=> rgw/cloud-restore: verify if the expiry-date is updated

s3tests_boto3/functional/test_s3.py
aws-chunked should not be persisted on upload for return on download
tests for https://github.com/ceph/ceph/pull/64440
=> s3: test for aws-chunked in Content-Encoding responses

s3tests_boto3/functional/test_s3.py
This is to extend the test case `test_versioning_obj_suspended_copy` to cover https://github.com/ceph/ceph/pull/65158
Signed-off-by: Jane Zhu [jzhu116@bloomberg.net](mailto:jzhu116@bloomberg.net)
=> extend test_versioning_obj_suspended_copy to test copy to another non-versioned bucket

s3tests_boto3/functional/test_s3.py
This is to test this PR: https://github.com/ceph/ceph/pull/65456
(cherry picked from commit ed614c19d02e9405c7212ad0cfc32e9db691a78e)
=> rgw/logging: fix cleanup tests for rollovers

s3tests_boto3/functional/test_s3.py
test coverage for https://github.com/ceph/ceph/pull/64830
multipart_put_object tests are duplicated to test non-versioned and overwrites of a current version
=> s3: test conditional multipart_put_object()
